### ISSUE TITLE
'NSInvalidArgumentException', reason: '+[FTIndicator showProgressWithmessage:userInteractionEnable:]: after Cocoapod update

### ISSUE THREAD

**Issue by LiamInJapan** [liufengting/FTIndicator#6]
Great library and very clean and easy to use, thanks very much!

One problem however... After updating via Cocoapods today I get the following error when trying to use the userInteractionEnable functionality:

'NSInvalidArgumentException', reason: '+[FTIndicator showProgressWithmessage:userInteractionEnable:]:

It's weird, as I can actually see the code in the FTIndicator source...

**Comment by liufengting** [comment]
I will look into it today. Sorry for the inconvenience.

**Comment by liufengting** [comment]
I tested it in both OC and Swift projects, using Cocoapods, I didn't get the same problem. Maybe you could clean the project, see if it works.
