### ISSUE TITLE
当吐司出现时，按下home键，吐司变小，但不消失

### ISSUE THREAD

**Issue by zhuyuping** [liufengting/FTIndicator#7]
当toast出现时，在还没有消失的情况下，按下home键，再回到程序，发现tosat还存在

**Comment by liufengting** [comment]
复现的概率高吗？

**Comment by liufengting** [comment]
在控件的-(void)dismissingProgressView方法里，动画结束的completion去掉if （finished）{}的判断，判断内的代码保留。

**Comment by liufengting** [comment]
代码已经提交了

**Comment by liufengting** [comment]
Bug Fixed.
